name: "GHAS Report"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: GitHub Advanced Security API to CSV
      # You may pin to the exact commit or the version.
      uses: advanced-security/ghas-to-csv@8c2ad35efb234e8e1bd12efaced0f0609ad8afbb
      # uses: advanced-security/ghas-to-csv@v3
    
    - name: Upload CSV
      uses: actions/upload-artifact@v3
      with:
        name: ghas-data
        path: ${{ github.workspace }}/*.csv
        if-no-files-found: error
